openapi: 3.0.0
info:
  description: This is a sample Journal server
  version: "1.0.0"
  title: Journal
servers:
  - url: http://localhost:8080/v2
tags:
  - name: auth
    description: Operations about authentication
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Add a new user
      description: ""
      operationId: addUser
      requestBody:
        description: New User will be added
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userDTO"
      responses:
        "200":
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        "422":
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
  /auth/login:
    post:
      tags:
        - auth
      summary: User login
      description: Authenticate a user and generate a token
      operationId: loginUser
      requestBody:
        description: Login credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestDTO"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationResponse"

components:
  schemas:
    userDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        postalCode:
          type: string
        role:
          type: string

    ResponseDTOWrapper:
      type: object
      properties:
        status:
          type: string
          example: SUCCESS
          description: Indicates the status of the response (e.g., SUCCESS or FAILURE).
        message:
          type: string
          example: "User successfully created"
          description: A descriptive message for the response.
        data:
          type: object
          description: The actual data being returned in the response.
          additionalProperties: true
          example:
            id: 123
            username: johndoe
    LoginRequestDTO:
      type: object
      properties:
        userEmail:
          type: string
        password:
          type: string

    AuthenticationResponse:
      type: object
      properties:
        access_token:
          type: string
          description: The access token used for authorization
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        refresh_token:
          type: string
          description: The refresh token used to obtain a new access token
          example: d93d0d93-d3c3-43d0-8c1d-d93d9d9c3...

    ChangePasswordRequest:
      type: object
      required:
        - oldPassword
        - newPassword
      properties:
        currentPassword:
          type: string
          description: The user's current password
          example: currentPassword
        newPassword:
          type: string
          description: The user's new password
          example: newPassword
        confirmationPassword:
          type: string
          description: The user's confirmation password
          example: confirmationPassword
